-- Cultiva Datos - Full Database Setup Script
-- Use this script to initialize a fresh Supabase project.

-- ============================================================
-- 1. TABLES
-- ============================================================

-- 1.1 Profiles (extends auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  name TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('god', 'admin', 'user')),
  kit_code TEXT,
  start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  score INTEGER DEFAULT 0,
  avatar TEXT,
  gender TEXT,
  birth_date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 1.2 Allowed Kits
CREATE TABLE IF NOT EXISTS public.allowed_kits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'available' CHECK (status IN ('available', 'claimed')),
  claimed_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  claimed_at TIMESTAMP WITH TIME ZONE,
  batch_id TEXT,
  kit_number TEXT, -- Added for UI display (e.g. "Kit 1")
  variety TEXT,    -- Added for UI display (e.g. "Roma")
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON COLUMN allowed_kits.kit_number IS 'Visual label number (e.g. "Kit 10")';
COMMENT ON COLUMN allowed_kits.variety IS 'Plant variety (e.g. "Cherry", "Roma")';

-- 1.3 Experiment Entries
CREATE TABLE IF NOT EXISTS public.experiment_entries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  day_number INTEGER,
  general_notes TEXT,
  -- pots JSONB, -- Deprecated in favor of 'pots' table, but kept if legacy needed (removed for clean setup)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 1.4 Pots (Details for each entry)
CREATE TABLE IF NOT EXISTS public.pots (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  entry_id UUID REFERENCES experiment_entries(id) ON DELETE CASCADE NOT NULL,
  pot_id TEXT NOT NULL, -- e.g. "1", "2", "3"
  weight NUMERIC,
  height NUMERIC,
  visual_status TEXT,
  ph NUMERIC,
  notes TEXT,
  images JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- 2. STORAGE
-- ============================================================

INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Policies for Storage are handled via SQL policies on storage.objects, see Section 5.

-- ============================================================
-- 3. FUNCTIONS & TRIGGERS
-- ============================================================

-- 3.1 Handle New User (Profile creation on Signup)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'name')
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    name = COALESCE(EXCLUDED.name, profiles.name);
  RETURN new;
END;
$$;

-- Trigger to call handle_new_user
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 3.2 Get My Role (Helper for RLS)
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
DECLARE
  retrieved_role text;
BEGIN
  SELECT role INTO retrieved_role FROM public.profiles WHERE id = (select auth.uid());
  RETURN retrieved_role;
END;
$$;

-- 3.3 Admin Upload Kits (RPC)
CREATE OR REPLACE FUNCTION admin_upload_kits_v2(
    kits_data jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    kit_record jsonb;
    inserted_count integer := 0;
    updated_count integer := 0;
    check_role text;
BEGIN
    -- 1. Check if user is admin
    SELECT role INTO check_role FROM profiles WHERE id = (select auth.uid());
    
    -- Relaxed check for dev/setup: Allow if role is admin OR god
    IF check_role NOT IN ('admin', 'god') THEN
        -- return jsonb_build_object('error', 'Unauthorized: Admin role required'); 
        -- For initial setup flexibility, we might want to allow this or ensure the first user is promoted manually.
        -- Keeping strict for security. User must manually update their role to 'god' in DB after signup.
        RAISE EXCEPTION 'Unauthorized: Only admins can upload kits.';
    END IF;

    FOR kit_record IN SELECT * FROM jsonb_array_elements(kits_data)
    LOOP
        INSERT INTO allowed_kits (code, kit_number, variety, batch_id, status)
        VALUES (
            kit_record->>'code',
            kit_record->>'kit_number',
            kit_record->>'variety',
            kit_record->>'batch_id',
            'available'
        )
        ON CONFLICT (code) DO UPDATE SET
            kit_number = EXCLUDED.kit_number,
            variety = EXCLUDED.variety,
            batch_id = EXCLUDED.batch_id,
            status = 'available'; -- Re-set to available if re-uploading? Maybe.
            
        updated_count := updated_count + 1; -- Simply counting processed
    END LOOP;

    RETURN jsonb_build_object(
        'success', true,
        'message', format('Processed %s kits', updated_count)
    );
EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;


-- ============================================================
-- 4. RLS POLICIES (Optimized)
-- ============================================================

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE allowed_kits ENABLE ROW LEVEL SECURITY;
ALTER TABLE experiment_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE pots ENABLE ROW LEVEL SECURITY;

-- 4.1 Profiles
CREATE POLICY "profiles_select_optimized" ON profiles FOR SELECT USING ((select auth.uid()) = id OR (public.get_my_role() IN ('god', 'admin')));
CREATE POLICY "profiles_insert_optimized" ON profiles FOR INSERT WITH CHECK ((select auth.uid()) = id);
CREATE POLICY "profiles_update_optimized" ON profiles FOR UPDATE USING ((select auth.uid()) = id OR (public.get_my_role() = 'god')) WITH CHECK ((select auth.uid()) = id OR (public.get_my_role() = 'god'));

-- 4.2 Allowed Kits
CREATE POLICY "kits_select_optimized" ON allowed_kits FOR SELECT USING (status = 'available' OR (public.get_my_role() IN ('god', 'admin')));
CREATE POLICY "kits_admin_manage_optimized" ON allowed_kits FOR ALL USING (public.get_my_role() IN ('god', 'admin')) WITH CHECK (public.get_my_role() IN ('god', 'admin'));
CREATE POLICY "kits_user_claim_optimized" ON allowed_kits FOR UPDATE USING (status = 'available' AND (select auth.uid()) IS NOT NULL) WITH CHECK (status = 'claimed' AND claimed_by = (select auth.uid()));

-- 4.3 Experiment Entries
CREATE POLICY "entries_select_optimized" ON experiment_entries FOR SELECT USING (user_id = (select auth.uid()) OR (public.get_my_role() IN ('god', 'admin')));
CREATE POLICY "entries_insert_optimized" ON experiment_entries FOR INSERT WITH CHECK (user_id = (select auth.uid()));
CREATE POLICY "entries_update_optimized" ON experiment_entries FOR UPDATE USING (user_id = (select auth.uid()) OR (public.get_my_role() IN ('god', 'admin'))) WITH CHECK (user_id = (select auth.uid()) OR (public.get_my_role() IN ('god', 'admin')));
CREATE POLICY "entries_delete_optimized" ON experiment_entries FOR DELETE USING (user_id = (select auth.uid()) OR (public.get_my_role() IN ('god', 'admin')));

-- 4.4 Pots
CREATE POLICY "pots_select_optimized" ON pots FOR SELECT USING (EXISTS (SELECT 1 FROM experiment_entries e WHERE e.id = pots.entry_id AND (e.user_id = (select auth.uid()) OR (public.get_my_role() IN ('god', 'admin')))));
CREATE POLICY "pots_insert_optimized" ON pots FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM experiment_entries e WHERE e.id = pots.entry_id AND e.user_id = (select auth.uid())));
CREATE POLICY "pots_update_optimized" ON pots FOR UPDATE USING (EXISTS (SELECT 1 FROM experiment_entries e WHERE e.id = pots.entry_id AND (e.user_id = (select auth.uid()) OR (public.get_my_role() IN ('god', 'admin')))));
CREATE POLICY "pots_delete_optimized" ON pots FOR DELETE USING (EXISTS (SELECT 1 FROM experiment_entries e WHERE e.id = pots.entry_id AND (e.user_id = (select auth.uid()) OR (public.get_my_role() IN ('god', 'admin')))));

-- 4.5 Storage Policies (Avatars)
-- Public Read
DROP POLICY IF EXISTS "Public Access to Avatars" ON storage.objects;
CREATE POLICY "Public Access to Avatars" ON storage.objects FOR SELECT USING ( bucket_id = 'avatars' );
-- Auth Upload
DROP POLICY IF EXISTS "Authenticated User Upload Avatar" ON storage.objects;
CREATE POLICY "Authenticated User Upload Avatar" ON storage.objects FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text );
-- User Update/Delete
DROP POLICY IF EXISTS "User Update Own Avatar" ON storage.objects;
CREATE POLICY "User Update Own Avatar" ON storage.objects FOR UPDATE TO authenticated USING ( bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text ) WITH CHECK ( bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text );
DROP POLICY IF EXISTS "User Delete Own Avatar" ON storage.objects;
CREATE POLICY "User Delete Own Avatar" ON storage.objects FOR DELETE TO authenticated USING ( bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text );


-- ============================================================
-- 5. SEED DATA (Kits)
-- ============================================================

INSERT INTO allowed_kits (code, kit_number, variety, batch_id, status) VALUES 
('CVPL-01', '1', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-02', '2', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-03', '3', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-04', '4', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-05', '5', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-06', '6', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-07', '7', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-08', '8', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-09', '9', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-10', '10', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-11', '11', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-12', '12', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-13', '13', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-14', '14', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-15', '15', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-16', '16', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-17', '17', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-18', '18', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-19', '19', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-20', '20', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-21', '21', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-22', '22', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-23', '23', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-24', '24', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-25', '25', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-26', '26', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-27', '27', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-28', '28', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-29', '29', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-30', '30', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-31', '31', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-32', '32', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-33', '33', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-34', '34', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-35', '35', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-36', '36', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-37', '37', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-38', '38', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-39', '39', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-40', '40', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-41', '41', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-42', '42', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-43', '43', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-44', '44', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-45', '45', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-46', '46', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-47', '47', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-48', '48', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-49', '49', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-50', '50', 'Cal Ace', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-51', '51', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-52', '52', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-53', '53', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-54', '54', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-55', '55', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-56', '56', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-57', '57', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-58', '58', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-59', '59', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-60', '60', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-61', '61', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-62', '62', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-63', '63', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-64', '64', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-65', '65', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-66', '66', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-67', '67', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-68', '68', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-69', '69', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-70', '70', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-71', '71', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-72', '72', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-73', '73', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-74', '74', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-75', '75', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-76', '76', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-77', '77', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-78', '78', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-79', '79', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-80', '80', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-81', '81', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-82', '82', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-83', '83', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-84', '84', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-85', '85', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-86', '86', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-87', '87', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-88', '88', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-89', '89', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-90', '90', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-91', '91', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-92', '92', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-93', '93', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-94', '94', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-95', '95', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-96', '96', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-97', '97', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-98', '98', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-99', '99', 'Roma', 'MANUAL_SEED_SCRIPT', 'available'),
('CVPL-100', '100', 'Roma', 'MANUAL_SEED_SCRIPT', 'available')
ON CONFLICT (code) DO NOTHING;

-- End of setup
